package de.kreuzwerker.adventofcode.day02

import java.lang.Error

class Game {
    var opponent: String = ""
    var player: String  = ""
    constructor(_opponent: String, _player: String) {
        opponent = _opponent
        player = _player
    }

    fun playerWon(): Boolean {
        return false
    }

    private fun converToPoints(char: String):Int {
        when (char) {
            "X" -> return 1
            "Y" -> return 2
            "Z" -> return 3
            else -> return 0
        }
    }

    fun score(): Int {
        val drawBasePoints = 3
        val wonPoints = 6
        val lostPoints = 0

        // A, X -> draw
        if (opponent == "A" && player == "X") return drawBasePoints + converToPoints(player)
        // A, Y -> win
        if (opponent == "A" && player == "Y") return wonPoints + converToPoints(player)
        // A, Z
        if (opponent == "A" && player == "Z") return lostPoints + converToPoints(player)

        // B, X
        if (opponent == "B" && player == "X") return lostPoints + converToPoints(player)
        // B, Y -> draw
        if (opponent == "B" && player == "Y") return drawBasePoints + converToPoints(player)
        // B, Z
        if (opponent == "B" && player == "Z") return wonPoints + converToPoints(player)

        // C, X
        if (opponent == "C" && player == "X") return wonPoints + converToPoints(player)
        // C, Y
        if (opponent == "C" && player == "Y") return lostPoints + converToPoints(player)
        // C, Z -> draw
        if (opponent == "C" && player == "Z") return drawBasePoints + converToPoints(player)

        throw Error("should not happen")

    }

    override fun toString(): String {
        return "opponent = ${opponent}, player = ${player} => ${score()}"
    }
}
class Day02 {

    fun solve(input: String): Int {
        val games = mutableListOf<Game>()

        input.lines().forEach {
            var g = Game(it[0].toString(), it[2].toString())
            println("line: " + it)
            games.add(g)

            println(g)
        }

        val sum = games.sumOf {  it.score()  }
        println("sum" + sum)

        return sum
    }

    companion object {
        val input = """
            C Y
            B Y
            C Y
            B X
            B X
            B X
            C Y
            B Z
            A Z
            A Z
            A Z
            A Y
            A X
            A Z
            A X
            A Z
            C Y
            A X
            A Z
            A Z
            A Z
            A Y
            C Y
            B Z
            B Z
            C Y
            C Y
            C Y
            C Y
            A X
            B Z
            C X
            B X
            A Y
            C X
            C Y
            C Y
            B X
            C X
            B Z
            C Y
            B X
            C Y
            B X
            B X
            C Y
            A X
            B X
            B Z
            B X
            A Z
            B Z
            B X
            B Y
            C Y
            A X
            C Y
            A Z
            C Y
            C Z
            B Z
            C Y
            C Y
            C Y
            B Y
            B X
            B X
            A X
            B Z
            B X
            B X
            B X
            B X
            B Y
            B X
            B X
            B X
            B X
            B Z
            B X
            B X
            B Y
            B X
            C Y
            C Y
            B Z
            A Z
            A X
            B X
            B X
            A X
            B X
            A X
            B X
            A Z
            B Y
            A X
            A Y
            C Y
            A X
            A X
            C Y
            A Z
            B X
            B Y
            C Z
            C Y
            B X
            B X
            A Z
            B X
            B X
            C Y
            A Z
            A Z
            B X
            C X
            B Z
            C Y
            B X
            A Y
            C Y
            B Z
            C Y
            B Z
            A X
            C Y
            C Z
            B X
            B X
            C X
            A X
            B X
            B Z
            B Z
            B Z
            A Y
            B Z
            B X
            C Y
            B Z
            A Z
            C Y
            C Y
            A Z
            C Y
            B X
            B X
            C Y
            B Z
            B Z
            C Y
            A X
            C Y
            C Y
            B X
            B Y
            C Y
            C Y
            A Z
            B Z
            B X
            B X
            C Z
            C Y
            A X
            B Z
            B Y
            C Y
            C Y
            B X
            B Z
            C X
            B X
            C Y
            B Z
            A X
            B X
            B Z
            A X
            C Y
            B X
            B X
            C Y
            A X
            B X
            B Y
            A X
            A Y
            C Y
            C Y
            B X
            A Z
            A X
            B Y
            A X
            A X
            C X
            C Y
            B Y
            A Z
            C X
            A X
            B Z
            B X
            B X
            C Y
            A X
            C X
            C Y
            A X
            C Y
            B X
            B X
            C Y
            C Y
            B X
            A X
            B X
            A X
            C Y
            B Y
            B Z
            B X
            B X
            C X
            C Y
            B Z
            C Y
            C Y
            B X
            A Z
            B Z
            A Z
            A Z
            C Y
            B X
            C Y
            C Y
            C X
            B X
            C X
            C Z
            C Y
            B Z
            C Z
            C Y
            A Z
            B X
            C X
            B Y
            B Z
            C Y
            B Z
            B Z
            B Z
            A Z
            C X
            A Y
            B Z
            A Z
            B Z
            B Y
            A Z
            C Y
            C Y
            B X
            A X
            B X
            C X
            B Y
            C Y
            B Z
            B X
            C Y
            A X
            B Z
            B Y
            C X
            C Y
            B X
            A Z
            A Z
            C Y
            B Z
            B Z
            B X
            B X
            C X
            B X
            B X
            B X
            A Z
            A X
            C Z
            B X
            A Z
            B X
            C X
            B X
            C X
            B Z
            B X
            B X
            A X
            B Z
            B Y
            A Z
            A Z
            C Y
            C Y
            A Z
            A Z
            B X
            A X
            B Z
            C X
            C Y
            C Y
            B Z
            A X
            B Y
            B Z
            A X
            C Y
            B Z
            A X
            B X
            B X
            C Y
            C Z
            A Y
            A X
            C Y
            A Z
            C X
            A Z
            A Z
            C X
            A X
            A Z
            B Z
            A Y
            A Z
            C Y
            B X
            B X
            B Z
            B X
            B X
            B Y
            B X
            B X
            C Y
            B X
            A Z
            B X
            C Y
            A Z
            B Z
            C Y
            C X
            C Y
            B X
            C Y
            B Y
            B X
            B Z
            C Y
            A X
            A X
            C X
            B X
            A X
            C X
            B Y
            B Y
            A Z
            C Z
            C Z
            A X
            C Y
            A Y
            A Z
            B Z
            A Z
            A X
            A Y
            B X
            B Y
            C Y
            A X
            B Y
            C X
            C Y
            B Z
            C Y
            A X
            B Z
            B Z
            A X
            C X
            B X
            A X
            B Z
            C Y
            C Y
            B Y
            A Y
            B X
            B Z
            B X
            C Y
            B X
            C Y
            C X
            A Z
            B Z
            C Y
            B X
            B Z
            B Z
            B Z
            C Y
            C X
            C X
            B X
            A X
            C Y
            C Y
            B X
            B Z
            C Y
            A X
            B X
            B Z
            B Z
            B Y
            A Y
            B X
            B Z
            B X
            A X
            A Z
            A Z
            C X
            B Y
            B Z
            C Z
            B X
            C Y
            B X
            C Y
            B Y
            B Z
            B Y
            B X
            A Z
            C X
            A X
            A Z
            C Y
            B X
            C Y
            C Y
            B X
            C Z
            B Z
            B Z
            C X
            C Y
            A Y
            C Y
            A Y
            B X
            B Y
            A Z
            B Z
            B X
            B X
            A X
            C Y
            B Z
            C Y
            B X
            A Z
            B Z
            C Y
            B Z
            A Z
            C Y
            B X
            B X
            C Y
            C Y
            C Y
            B X
            C Z
            B Z
            B X
            C Y
            C X
            B X
            C Y
            B Y
            B Z
            B Z
            B Y
            B Z
            B Y
            A Z
            B X
            B X
            A Z
            C Z
            A Z
            B X
            C Z
            A X
            B X
            C Y
            B Z
            A Z
            C Y
            C Y
            B Z
            A X
            C Y
            A Z
            B X
            B Z
            B Y
            B X
            B Z
            B X
            C Y
            A X
            B Z
            C Y
            B Z
            B Z
            C Y
            B X
            B X
            A Y
            C Y
            B Z
            B Z
            B X
            B Z
            A X
            A X
            C Y
            B X
            C Y
            A Z
            A X
            B X
            C Y
            B Z
            A Z
            B X
            A X
            B X
            B Y
            A X
            C Z
            A X
            B Y
            B X
            A Y
            C Y
            A Z
            B X
            C Y
            A X
            B X
            C Y
            A Z
            B Y
            A Z
            B Z
            B X
            A X
            B Y
            A X
            A Z
            B Z
            B X
            B Z
            C Y
            C Y
            C Y
            B X
            B Y
            A Z
            A Z
            B X
            B X
            B Y
            A X
            A Z
            C Y
            A Y
            B Z
            A X
            C X
            A Z
            C X
            C Y
            C Y
            B X
            B X
            B Z
            A X
            A Z
            B Y
            B Z
            B X
            B Z
            B X
            C Y
            B X
            C Y
            C Y
            B X
            B X
            C Z
            C Y
            A X
            A Z
            C Y
            C Y
            A X
            A Z
            A X
            C Y
            C Y
            B X
            A X
            C Y
            B X
            B X
            A Z
            B X
            A Z
            A Z
            C Y
            C Y
            B X
            C Y
            B X
            A X
            C Y
            B Z
            A X
            C Y
            B Z
            A X
            A Z
            C Y
            C Y
            B X
            A X
            B X
            B Z
            A Z
            C X
            B Z
            A X
            B Z
            C Y
            B X
            A Z
            C X
            B Z
            A Z
            A X
            C Y
            B X
            C Y
            B X
            A Z
            B Z
            B X
            C X
            B Z
            B Y
            C Y
            B Z
            B Z
            B Z
            B Z
            C Y
            C Y
            A Z
            C Y
            C Z
            C Z
            C Y
            C Y
            B Z
            A Y
            B X
            A Y
            B Z
            A Z
            C Z
            B X
            B X
            C X
            A Z
            C Y
            A Z
            B X
            B X
            A X
            B Z
            B X
            C X
            A Z
            B Y
            A X
            B X
            A Z
            A X
            B Z
            C Y
            B X
            B X
            C Y
            C Y
            B X
            A Y
            C X
            B X
            C X
            B Y
            B X
            C Y
            C Y
            B X
            A Z
            A Z
            A Y
            B Z
            B Z
            B Z
            C Y
            A X
            B X
            C Y
            C Y
            A X
            C Y
            A Z
            B X
            A X
            A Y
            B Z
            B Y
            B Y
            C X
            A Z
            A Z
            B Z
            A Z
            B Z
            B X
            A Z
            B Z
            B Y
            B X
            B X
            B X
            A Y
            A X
            B X
            B X
            A X
            C Y
            B Z
            C Y
            B Y
            A X
            B Z
            A Z
            C Y
            A X
            C Y
            B X
            B Z
            B Z
            C Y
            B Z
            C Y
            B X
            C Y
            A Z
            A X
            B X
            C Y
            A X
            A X
            C Y
            C X
            C Y
            A Z
            B Z
            A X
            C X
            C X
            C Y
            B X
            C X
            A X
            C Y
            B Y
            A X
            C Y
            B X
            A Z
            C Y
            C Y
            A X
            A X
            B X
            B Y
            B Y
            A Y
            A X
            C Y
            A X
            C X
            B X
            C Y
            C Y
            A X
            A Z
            B Z
            B Z
            C Y
            B Z
            B Y
            A X
            C X
            C X
            A X
            C Y
            B Z
            A Z
            B X
            C Y
            C Y
            C X
            C Y
            C X
            A X
            C Y
            B X
            C X
            B X
            A Z
            B Z
            B Z
            B Z
            B X
            B Z
            B X
            B Y
            C Y
            C X
            A Y
            B Z
            B Y
            C Y
            B Z
            A X
            A X
            A Z
            C Y
            A X
            C X
            C Y
            B Y
            B X
            B X
            A X
            B Y
            C Y
            B X
            C X
            C X
            A Z
            A Z
            C Y
            B X
            B Z
            C Y
            B Z
            B Z
            C Y
            C X
            A X
            B Z
            C Y
            C Y
            C Y
            B Z
            B X
            C Y
            B Z
            A X
            B X
            C Y
            A Z
            C Y
            A Z
            A Z
            B Z
            C Y
            A Z
            C Y
            B X
            A X
            A X
            B Z
            C Y
            B Y
            B X
            A Z
            B X
            C Y
            A Z
            C Y
            A X
            A Z
            B X
            B X
            B Y
            B X
            A Z
            C Y
            A X
            C Y
            C Y
            C Y
            C Z
            C Y
            A Z
            A Y
            B Z
            C Y
            B X
            C Y
            C Y
            A Z
            C Z
            C Y
            B X
            C Y
            A Z
            B Z
            B Y
            B Z
            A Z
            B X
            B X
            C X
            B X
            B Z
            A X
            C Y
            C Y
            C Y
            A Z
            B X
            B Y
            A X
            A Z
            C Y
            A Z
            A Z
            B X
            C Y
            B Z
            B Z
            B X
            C X
            A Z
            C X
            B Z
            C Y
            A Z
            B X
            C Y
            B X
            A X
            C Z
            C X
            C Y
            A Z
            C Y
            B X
            B X
            B X
            B X
            B X
            A Y
            C Y
            B X
            A X
            A Z
            A Z
            A X
            C Z
            B Z
            C Y
            B X
            B Z
            A X
            B X
            B X
            C Y
            B X
            C Y
            A Z
            A Z
            C X
            B Z
            A X
            C Y
            B X
            C Y
            C Y
            C Y
            B X
            B Y
            A Z
            C Y
            C Y
            A X
            A X
            C Y
            B X
            B Z
            C Y
            A X
            C Z
            B Z
            B X
            C Y
            C Y
            B Z
            A X
            A Z
            B X
            C Y
            A Z
            A X
            A Y
            C Y
            B X
            B Z
            A X
            B Z
            B Z
            C Y
            C Y
            C X
            B Z
            A X
            C Y
            B Y
            A Z
            B X
            B Y
            B X
            C Y
            A Z
            B X
            A Z
            C Y
            B X
            B X
            C Y
            B Y
            C Y
            C Y
            C Y
            B X
            A X
            C Y
            C Y
            C Y
            A Z
            C Y
            B X
            B X
            B X
            B X
            A X
            B Y
            C X
            B X
            C X
            A X
            C X
            C Y
            A X
            A Z
            C Y
            B Z
            B Y
            A X
            B Y
            C Y
            C Y
            B X
            A X
            A X
            C X
            B Z
            C Y
            C Y
            A Z
            B Z
            B Z
            C X
            C Y
            B X
            B X
            B Z
            A Z
            C Y
            C Y
            A Z
            A Z
            B X
            B X
            B Y
            B Z
            B Z
            A Y
            B Z
            A Z
            B Z
            B X
            B Z
            C Z
            B Z
            A Z
            B Z
            B X
            B X
            B X
            A X
            C Y
            A Z
            C Y
            C Y
            B X
            A Z
            C X
            B Z
            B Y
            C Z
            B X
            C Y
            A X
            C Y
            A Y
            B Z
            C Y
            C Y
            B X
            B X
            A Z
            C X
            A X
            A Z
            B Y
            C Y
            C Y
            C Y
            B X
            C Y
            C Y
            A Z
            B X
            A Z
            C X
            C Y
            B Z
            B Z
            B Z
            A Z
            C Y
            C Z
            B Z
            C Y
            C Y
            C Y
            B X
            B X
            C Y
            C Y
            B X
            A X
            A Z
            B X
            C Y
            B X
            A Z
            C Y
            C Y
            B Y
            A X
            A X
            A X
            A X
            B X
            B Y
            C Y
            A Z
            B Y
            B Z
            A X
            B X
            C Y
            A Y
            C Y
            A Z
            B X
            B Z
            B Z
            A Y
            B X
            B X
            C Y
            A Z
            A Z
            A X
            A X
            B Z
            C Y
            B Z
            C X
            A Z
            C Y
            B Z
            C Y
            C Y
            B Z
            A Z
            C Y
            C X
            A Z
            C Y
            B X
            A Y
            A X
            B Z
            A Y
            A Z
            B X
            C X
            B Z
            C Y
            C Y
            B Y
            B Z
            A X
            B X
            A Z
            C Y
            C Y
            A Z
            A Z
            B X
            C Y
            B Z
            A X
            A X
            B X
            B Y
            C Y
            B X
            C X
            C Y
            B Z
            A Z
            A Y
            B X
            C Y
            C Y
            C X
            A Z
            C Z
            B Z
            B X
            A Z
            A X
            A X
            B Z
            B X
            A Z
            B Z
            C Y
            A X
            B Z
            B Z
            C Y
            C Y
            A X
            B X
            C Y
            A X
            B X
            C Y
            B X
            A Z
            A X
            B Z
            A Z
            B Z
            B Y
            A X
            B Z
            A Z
            A Z
            A Z
            A X
            A X
            B X
            B X
            A Z
            B Y
            A Y
            C Y
            B X
            C Y
            B Y
            C Y
            A Z
            A Z
            B X
            B X
            C Y
            B Z
            C Y
            B Z
            B X
            B X
            B X
            B X
            A X
            B Y
            B X
            C X
            A Z
            A Z
            B X
            C Y
            C Y
            C Y
            A X
            C Y
            C Y
            C Y
            A X
            C Y
            C X
            B X
            A Y
            C Z
            C Y
            A Z
            B X
            A Z
            A X
            B X
            A X
            A X
            C Y
            A Y
            A X
            B X
            A Z
            B Z
            B Y
            C Z
            B X
            A Z
            C Y
            B Z
            B X
            C Y
            C Y
            C Y
            B X
            A X
            A Z
            B X
            A X
            C Y
            B Z
            A X
            C Y
            C Y
            A X
            A X
            A X
            A Y
            C Y
            C Y
            C Y
            C Z
            C Y
            A X
            B X
            C Y
            C Y
            C Y
            C Y
            A X
            B Z
            A X
            B X
            C Y
            B Z
            A Z
            C Y
            A Z
            C Y
            B X
            B X
            C Y
            C Y
            B Y
            A X
            C Y
            C X
            C Y
            C X
            A Z
            A Z
            B Y
            A X
            A X
            B Z
            A Z
            A X
            A Z
            C Y
            A X
            B Z
            C X
            A X
            A X
            B X
            A X
            B Y
            A X
            B X
            B X
            C Y
            C X
            B X
            B Y
            C X
            A Z
            B Z
            B X
            C Y
            B Y
            B Z
            C Y
            A X
            C Y
            B X
            B X
            C Y
            C Z
            B X
            B X
            C X
            B Y
            B Y
            B Z
            C X
            B X
            C Y
            B X
            C Y
            B X
            A X
            A Y
            B X
            B X
            B X
            B Y
            C Y
            B X
            B X
            B X
            C Y
            A Z
            B Z
            B X
            A Z
            B X
            B Y
            C X
            A Z
            C Y
            C Y
            B Z
            B X
            C Y
            C Y
            C Y
            C Y
            B Z
            A X
            C Y
            C Y
            A Z
            B X
            B Z
            A Y
            C Y
            B X
            C Z
            A Z
            B Y
            A Y
            A Z
            A Z
            B X
            B X
            C X
            A Z
            B Z
            A X
            B Z
            A Z
            B X
            B X
            C Y
            B Z
            C Y
            A Z
            B Z
            B X
            A Z
            C Y
            B X
            B Y
            B Z
            C Y
            B X
            C Y
            B X
            A X
            A X
            C Y
            B X
            B X
            A Y
            A Z
            A Z
            B Z
            A Z
            C Y
            C Y
            A Z
            A X
            A Z
            B X
            C Y
            C X
            A Z
            A X
            B Z
            B Z
            A X
            B X
            C X
            C Y
            C Y
            B Z
            B X
            C Y
            C Z
            B Y
            C Y
            A Z
            B Z
            B Z
            B X
            B X
            C Y
            B X
            B X
            C X
            A X
            B Z
            C Y
            B Y
            B X
            A Z
            B Z
            B X
            A Z
            B Z
            B X
            A Z
            B X
            C Y
            C X
            B Y
            B Y
            B Z
            C Y
            A X
            B Z
            B Y
            C Y
            A X
            B Z
            B Z
            C X
            B X
            C Y
            C Y
            C Y
            C Y
            A Z
            A Z
            B X
            B X
            C Z
            B X
            B Z
            B X
            B Z
            A Z
            B X
            C Y
            B X
            C Y
            C Y
            A X
            B X
            A X
            C X
            B X
            B Y
            A X
            B Z
            A Z
            B Y
            B Z
            C Y
            B Z
            C Y
            B X
            B Z
            B Y
            B X
            B X
            A Z
            B Z
            B X
            A Z
            C Y
            C Y
            A Z
            A X
            C Z
            A X
            B Z
            B Z
            C Y
            B X
            B X
            A Y
            B Z
            C X
            C Y
            C Y
            C Y
            A Y
            A X
            B X
            B Z
            A Z
            B X
            C X
            C X
            C Y
            C Y
            C Y
            B X
            B X
            A Z
            B Z
            B X
            A X
            A Z
            C Z
            B Z
            B Z
            B X
            A X
            B X
            C Y
            B Z
            A X
            B Y
            B Z
            B Y
            B X
            A X
            B Z
            C Y
            C X
            C Y
            A Z
            B Z
            B X
            B Z
            B X
            A Y
            B X
            A Z
            B X
            C X
            A X
            C Y
            B X
            C Y
            C Y
            A Y
            C Z
            A Z
            C X
            B X
            C Y
            A Z
            B X
            B Z
            B Z
            C Y
            A X
            A Z
            B X
            B X
            B Z
            B X
            C Y
            B X
            A X
            A X
            C Y
            A Z
            C Y
            B Y
            B Z
            B Z
            C Y
            B Z
            C Y
            B X
            B X
            B Y
            C Y
            A X
            A Z
            A Z
            A X
            C Y
            B X
            B Y
            B Y
            B X
            A X
            A Y
            B Y
            B Y
            C Y
            A X
            B Z
            C Y
            A Z
            C Y
            B Y
            A X
            B X
            A X
            B X
            A Z
            C Y
            C Y
            A X
            B Y
            B Y
            B X
            A Z
            A Z
            A Z
            A Y
            B Z
            C X
            B X
            C Y
            C Z
            B Y
            C Y
            C X
            B X
            B Z
            B Z
            B Z
            B Z
            B Y
            B Z
            A Z
            C X
            B X
            C Y
            C Y
            B Z
            C Y
            C Y
            A X
            C X
            A X
            B Z
            C Y
            B X
            C Y
            A X
            A Z
            C Z
            A X
            B Z
            C Y
            C Y
            C Y
            A X
            C Y
            C Y
            B X
            B X
            B Y
            C Y
            B Z
            B X
            C Y
            A Z
            C X
            A Z
            C Y
            A Z
            A X
            B Z
            B X
            C Z
            B X
            C Y
            A Z
            C Y
            B X
            B X
            B X
            B Z
            C Y
            B X
            A Z
            A Z
            C Y
            B Y
            C Y
            B Z
            A Z
            A X
            B Z
            B X
            B X
            A Y
            B X
            B X
            C Y
            B X
            B X
            B Z
            C Y
            B X
            A X
            A Z
            A Z
            C X
            A X
            A X
            B X
            B X
            B Z
            A X
            C Y
            B X
            C Y
            C Y
            A X
            B X
            A X
            A Z
            A Z
            C Y
            B X
            C Y
            B Y
            B X
            B X
            C X
            B X
            A X
            C X
            B Z
            C Y
            B Z
            B X
            C Y
            C Y
            A Z
            C Y
            B Z
            B X
            A Z
            C Y
            C Y
            B X
            B Z
            A X
            B X
            C Y
            C Y
            C Y
            A X
            A X
            A X
            B Z
            B Z
            A X
            A X
            B X
            B Z
            C Y
            C Y
            B Z
            A Z
            C Y
            C Y
            A Z
            B Z
            C Y
            B X
            B X
            B X
            C Y
            C Y
            B Z
            C Y
            B Z
            A X
            A X
            B X
            C Y
            A X
            A X
            C X
            A Y
            C X
            B X
            B X
            B Z
            B Z
            B Z
            B X
            B Z
            C Y
            C Y
            C X
            A Z
            B X
            A X
            B Z
            B X
            A Z
            C Y
            B X
            B Y
            B Z
            A Z
            B X
            A Y
            C X
            B X
            C Z
            C Y
            B Z
            A X
            B Z
            B Z
            A X
            B Z
            B X
            C Y
            B Z
            C X
            C Y
            A Z
            C Y
            A Y
            B Z
            B X
            B Y
            A Z
            A Y
            A X
            B Y
            A Z
            B Z
            C Y
            C Y
            C X
            C Y
            C Y
            B X
            B Z
            A Z
            B Z
            B Z
            A Z
            C Y
            A Z
            C X
            C Y
            C Y
            C Y
            A X
            C Y
            B Z
            A X
            C Y
            C Y
            C Y
            B X
            B Z
            B Y
            C Y
            C Y
            C Y
            C Y
            B Y
            A Y
            B Z
            B X
            A X
            A Y
            C Y
            C X
            B X
            B Z
            A Z
            B Z
            B X
            A X
            C Z
            C X
            B Z
            C Y
            A X
            C X
            B Z
            B X
            B X
            A Z
            B X
            B Z
            B Y
            C Y
            B X
            A X
            B X
            B Z
            A X
            B Z
            A Y
            C Y
            A X
            C X
            B X
            B Y
            B Z
            B X
            B X
            C Y
            B X
            B X
            C Y
            B Y
            B Z
            B Y
            B Z
            C Y
            A Z
            C Y
            A Z
            B X
            B X
            A Z
            B X
            C Y
            C X
            C Y
            B Y
            C Y
            C Y
            C Z
            C Y
            A Y
            C Y
            B X
            B Z
            A Y
            B Z
            A Z
            B Z
            B Z
            B X
            B Y
            C Y
            B X
            C Y
            C Z
            C Y
            A X
            B X
            B X
            C Z
            A Z
            B X
            A Z
            C Y
            B Z
            B Z
            B Y
            A Z
            B Z
            C Y
            C Y
            A Z
            C Y
            B Y
            C Y
            B Z
            C X
            B Z
            B X
            A Z
            B Y
            B Y
            B Z
            A Z
            B Z
            C X
            C X
            B Z
            B X
            C Y
            B X
            A X
            B X
            B X
            B Z
            C Y
            A Z
            A Y
            B Z
            C Y
            A X
            A X
            A Y
            B X
            B Z
            A X
            B X
            C X
            B X
            B Y
            B X
            A Z
            C Y
            A X
            C Y
            A X
            C Y
            C Y
            B Y
            C Y
            B X
            C Y
            C Y
            B X
            B Z
            A X
            C Y
            C X
            C X
            C Y
            B Y
            A Z
            C Y
            A X
            A X
            B X
            B X
            A X
            B X
            C X
            B Z
            B X
            A X
            A Z
            B X
            C Y
            C Y
            A X
            C X
            B Z
            B Z
            B X
            C Y
            C Y
            A Z
            C X
            B Z
            C Y
            B Y
            A Z
            B Z
            A Z
            B X
            C X
            C Z
            C Y
            A Z
            B Z
            B X
            C Y
            C Y
            C X
            C Y
            C Y
            C Y
            A X
            A Z
            C Y
            B X
            B X
            B Z
            A Z
            C Y
            B X
            A Z
            C Y
            C Y
            B Z
            A X
            B Z
            B Z
            B X
            B Z
            B X
            B X
            B Z
            B Z
            C Y
            A X
            A X
            A Z
            C Y
            C Y
            B X
            B Z
            C Z
            B X
            C Z
            C Y
            C X
            C Y
            B Y
            A X
            B Z
            A Z
            C X
            B X
            C X
            A Z
            A Y
            B Z
            A X
            A X
            A Z
            A Z
            B Y
            B Z
            C Y
            B X
            C Y
            B Z
            B X
            C Y
            C Y
            A X
            A Z
            B X
            C Y
            B X
            B X
            A X
            A Z
            B X
            B X
            B Z
            A X
            A X
            B Z
            B X
            B X
            B X
            A Z
            C X
            B X
            B X
            B X
            B Z
            B X
            C X
            C Y
            A Z
            C X
            A Z
            C Y
            A X
            C Y
            A X
            B X
            A Z
            B X
            C Y
            C Y
            A Z
            A Z
            B Z
            B Z
            B X
            C X
            A X
            B Y
            B Z
            C Y
            B Z
            A X
            A X
            B X
            A X
            A X
            A X
            A X
            B Z
            B Y
            C Y
            A Z
            C Z
            C Y
            A X
            B Y
            C X
            A Z
            B X
            B Z
            A X
            A X
            C Y
            B X
            B X
            A X
            A Z
            C Y
            C Y
            A Z
            C Y
            B X
            B X
            A Z
            A Y
            C Y
            A Z
            A X
            C Y
            B Z
            B Z
            C Y
            B X
            C Y
            C Y
            C Y
            C Z
            B X
            C Y
            C X
            B Z
            A Z
            C Y
            A Z
            B Z
            A Z
            B X
            A X
            A Z
            B Z
            B Z
            A X
            B Z
            A X
            B X
            A Z
            B X
            B X
            A Z
            C Y
            B X
            B Z
            C Y
            B Z
            B Z
            B X
            B Z
            B X
            B X
            C Y
            B X
            B Y
            B X
            B X
            A Z
            B X
            C Y
            B X
            B X
            B X
            B Z
            A Z
            B Y
            B X
            B Z
            C X
            C Y
            B X
            B Y
            C Y
            B X
            C X
            B X
            C X
            B Z
            A Y
            A Z
            B Z
            B Z
            A X
            A Z
            B Z
            B X
            A Z
            B Z
            C Y
            C Z
            C Y
            A Z
            C Z
            A Z
            C Z
            C Y
            A Z
            A Y
            C Y
        """.trimIndent()
    }
}